# Generated by Django 3.0.3 on 2020-04-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corona',
            old_name='name',
            new_name='country',
        ),
    ]
